### ISSUE TITLE
Discussion: Tracking decomp time

### ISSUE THREAD

**Issue by ethteck** [ethteck/decomp.me#1]
This has been brought up as a user metric (total time spent), but I'm not sure I personally think it's a good idea to have it on the website. I was wondering what others think.

Even if we don't display time spent on the website, there may be other uses for tracking time spent on individual functions and such. However, this might be hard to do..not sure

**Comment by notyourav** [comment]
If this is something being tracked across sessions/functions, I would think simply counting the number of bytes decompiled would be good enough. That is really the only thing we can confidently measure.
