### ISSUE TITLE
Front-end bugs

### ISSUE THREAD

**Issue by ethteck** [ethteck/decomp.me#10]
- [x] when loading the page, an invalid compile request is submitted (only contains a null compiler config)
- [x] the scratch's compiler config is not selected in the dropdown (it's always the first one in the list)
- [x] selecting a new compiler config invokes the compiler command as it should, but it uses the old config, not the one that was just chosen
- [ ] ctrl+or ctrl- to change browser zoom setting breaks the page
- [x] (opinion) the list of compiler configs shouldn't be reloaded every time you focus back on the webpage

**Comment by nanaian** [comment]
> ctrl+or ctrl- to change browser zoom setting breaks the page
As discussed this is mostly an issue with a dependency and in non-dev environments the error will only show in the JS console with (hopefully) no ill effects
