### ISSUE TITLE
Jenkinsfile and Jenkins project to update the site

### ISSUE THREAD

**Issue by ethteck** [ethteck/decomp.me#103]
Once we have some tests (#95), I'll write a Jenkinsfile for the repo and configure a Jenkins project to run tests on branches / PRs as well as update the site on updates to the main branch if tests pass.

**Comment by ethteck** [comment]
Now that we'll be doing most of our CI in github actions, and due to the ever-changing nature of the env file and site configuration and stuff, I wanna advocate for not auto-updataing the site after pushes to main but instead doing so manually after things are all passing.

One example of where this would go wrong with automatic updating: for the new github work, the prod .env file wouldn't contain the github app id/secret and then the site's github connection would break. I wrote #111 to handle running the backend tests in CI.

Closing for now, but we can re-visit  / re-open later on if people don't like my proposal

**Comment by nanaian** [comment]
> for the new github work, the prod .env file wouldn't contain the github app id/secret and then the site's github connection would break.
I considered this; the GitHub support gracefully falls back if the client ID isn't set - the button is disabled on the frontend.
I think we should still do CI.
