### ISSUE TITLE
Diff script failure causes compile request to hang

### ISSUE THREAD

**Issue by ethteck** [ethteck/decomp.me#109]
https://decomp.me/scratch/ffVOS

This scratch produces a diff.py error - we should be returning some error to the user (not necessarily the stack trace, but *something*) instead of just hanging.

**Comment by ethteck** [comment]
The linked scratch no longer produces a diff.py error, so I'm not sure if this is still an issue or not..

**Comment by ethteck** [comment]
Due to the standardization of return values in asm_diff_wrapper.py , I think this is fixed. Closing and we can re-open if we see that it's not

**Comment by simonlindholm** [comment]
Still unfixed from what I can see: we should try-catch the diff process. This only comes up in error cases though, so it's not super important.
