### ISSUE TITLE
ngx_brotli

### ISSUE THREAD

**Issue by nanaian** [ethteck/decomp.me#116]
Install the nginx brotli module on critter, and uncomment the lines I added to `sites-available/decomp.me` which enable it.
It's important that we try to reduce the amount of data sent over the wire, especially with #115 (the diff JSON is _much_ more verbose than HTML).
We should also make `yarn build` emit precompressed `.br` versions of the JS.

**Comment by ethteck** [comment]
I believe this is done. Is there any way to verify?

**Comment by ethteck** [comment]
that is, the nginx part is done. no clue how to do the yarn build change

**Comment by ethteck** [comment]
thanks broccoli
