### ISSUE TITLE
View/edit context in scratch view

### ISSUE THREAD

**Issue by ethteck** [ethteck/decomp.me#14]
Allow users to view / edit c context in the scratch view via a collapsible text panel

**Comment by nanaian** [comment]
Doesn't C context only affect mips2c, which is only done at scratch creation time?

**Comment by ethteck** [comment]
C context is used at compile time, because without type definitions and struct definitions, the function won't build. 
discussion: https://discord.com/channels/688807550715560050/859699601971609610/868091540294217788
