### ISSUE TITLE
Only allow scratch creators to update a scratch

### ISSUE THREAD

**Issue by ethteck** [ethteck/decomp.me#20]
how do

For owners (first visit to the scratch), they can save their scratch or fork it.
For non-owners, they can fork the scratch.

For now, let's consider the implementation of the fork button but perhaps not add the feature until the next iteration

**Comment by ethteck** [comment]
@nanaian on second thought, I think the buttons should always be visible to everyone and just disabled based on what you can do. A UI that changes seems kinda cool in some ways but the inconsistency might be a little confusing I fear, since the ownership system is kind of loose and not based off of accounts or anything. Also I think being able to hover over a grey save button and see a hover-over text "you can't save to this scratch because you're not the owner" would be nice.

**Comment by nanaian** [comment]
Works for me. I'd vote for ctrl+s to fork if saving is disabled, though
