### ISSUE TITLE
Scratch forking

### ISSUE THREAD

**Issue by ethteck** [ethteck/decomp.me#26]
Allow users to create forks from scratches 

- [ ] Add the fork button to the scratch view and allow anyone to click it to create a fork
- [ ] ctrl+s forks for non-owners? (I wanna ask people if this inconsistency with hotkey behavior will be confusing - probably fine though)
- [ ] Store the parent scratch into the new scratch and provide a link to the scratch's parent on the front-end

**Comment by mkst** [comment]
https://en.m.wikipedia.org/wiki/Pork_scratching
