### ISSUE TITLE
Front end shenanigans

### ISSUE THREAD

**Issue by ethteck** [ethteck/decomp.me#32]
- [x] padding on .log
- [x] display:block on log so it can scroll (or make it so the log/diff combo itself can be scrolled?)
- [x] label for the source code so it doesn't look like the context label applies to it 
~~- [ ] "Compiling..." text on the toolbar when we are waiting for a compile request to go through~~
- [x]  make compile button un-pressable and visually disabled while a compile request is going through
~~- [ ] "unsaved changes" text somewhere if the scratch was changed after page load~~
~~- [ ] maybe have a general status text field that shows "unsaved changes" / "compiling" / etc~~
- [ ] #60
- [x] make the context window size draggable (on the bottom edge)
- [x] allow dragging the code vs diff slider further on both directions
- [x] show warnings checkbox (enabled by default) that, when disabled, hides the log except for compilation failure
- [x] change aesthetic (standardize fonts, remove glow, make things more uniform)
- [x] there are issues scrolling the code area when the context is open
- [ ] #61
- [ ] #62

**Comment by nanaian** [comment]
#46 fixes a bunch of these; I've checked them off

**Comment by ethteck** [comment]
Closing in favor of the specific issues opened up for the 3 remaining tasks
