### ISSUE TITLE
link to parent scratch if what we're looking at is a fork

### ISSUE THREAD

**Issue by ethteck** [ethteck/decomp.me#62]

**Comment by nanaian** [comment]
Related: would be nice to have an API call that recursively lists the "fork tree" of a particular scratch via fancy database queries. e.g
```
GET /scratch/asdf/forks
{
    "slug": "asdf",
    "forks": [
        { "slug": "asdf2", "forks": [] },
        { "slug": "asdf3", "forks": [ /* etc */ ] }
    ]
}
```
Then the frontend can display a git-like branch view. It'd also be cool to have the backend track matched-ness so forks that match can be displayed 😉
